package com.ui.presagewebui;


import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;



@SuppressWarnings("serial")
public class AppViewController extends CustomComponent {
	
	private AbsoluteLayout mainLayout; /*Container layout for all the components*/

	private TabSheet sheet; /*Tab sheet providing access to multiple states of the app
	 						 * for example: Dashboard, Settings*/

	private VerticalLayout settingsLayout;
							/*Settings panel: should include settings such as 
							 * 1) Refresh rate
							 * 2) Database info
							 * and so on*/

	private MainScreenController mainScreenController;
							/*Contains layout for the tree*/

	
	/*=====================STATIC COMPONENTS BEGIN=====================*/
	private HorizontalLayout footer;
							/*Static layout for footer*/

	private Label copyrightLabel;
							/*copyright label to go in the footer*/

	private HorizontalLayout header;
							/*Static header*/
	private Label topLabel;

	
	/*=====================STATIC COMPONENTS END=====================*/

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AppViewController() {
		this.setImmediate(true);
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// header
		header = new HorizontalLayout();
		header.setImmediate(false);
		header.setWidth("100.0%");
		header.setHeight("60px");
		header.setMargin(false);
		mainLayout.addComponent(header, "top:0.0px;left:0.0px;");
		
		// footer
		footer = buildFooter();
		mainLayout.addComponent(footer, "top:560.0px;left:0.0px;");
		
		// sheet
		sheet = buildSheet();
		mainLayout.addComponent(sheet, "top:130.0px;right:8.0px;left:20.0px;");
		
		topLabel = new Label();
		topLabel.setImmediate(false);
		topLabel.setWidth("100.0%");
		topLabel.setHeight("49px");
		topLabel.setValue("Presage2 Web UI");
		mainLayout.addComponent(topLabel,
				"top:81.0px;right:339.0px;left:590.0px;");
		
		return mainLayout;
	}

	private HorizontalLayout buildFooter() {
		// common part: create layout
		footer = new HorizontalLayout();
		footer.setImmediate(false);
		footer.setWidth("100.0%");
		footer.setHeight("55px");
		footer.setMargin(true);
		
		// copyrightLabel
		copyrightLabel = new Label();
		copyrightLabel.setImmediate(false);
		copyrightLabel.setWidth("-1px");
		copyrightLabel.setHeight("-1px");
		copyrightLabel.setValue("©2011");
		footer.addComponent(copyrightLabel);
		footer.setComponentAlignment(copyrightLabel, new Alignment(24));
		
		return footer;
	}

	private TabSheet buildSheet() {
		// common part: create layout
		sheet = new TabSheet();
		sheet.setImmediate(false);
		sheet.setWidth("100.0%");
		sheet.setHeight("420px");
		
		/*mainScreeController: This screen will
		 * contain the treeLayout which will be the
		 * point of interaction with the user*/ 
		
		mainScreenController = new MainScreenController();
		mainScreenController.setImmediate(false);
		mainScreenController.setWidth("100.0%");
		mainScreenController.setMargin(false);
		sheet.addTab(mainScreenController, "Dashboard", null);
		
		// settingsLayout
		settingsLayout = new VerticalLayout();
		settingsLayout.setImmediate(false);
		settingsLayout.setWidth("100.0%");
		settingsLayout.setHeight("100.0%");
		settingsLayout.setMargin(false);
		sheet.addTab(settingsLayout, "Settings", null);
		
		return sheet;
	}

}
